import type { GameEU, GameJP, GameUS } from '../src';

export const JAPANESE_GAME: GameJP = {
  LinkURL: '123456789123456789',
  Hard: 'sample',
  LinkTarget: 'sample',
  MakerName: 'sample',
  Memo: 'sample',
  D: new Date().getTime(),
  SalesDateStr: 'sample',
  ScreenshotImgURL: 'https://example.com/HAC12345',
  ComingThumb: 'sample',
  ThumbVariation: 'sample',
  SoftType: 'sample',
  TitleName: 'sample',
  TitleNameRuby: 'sample',
  InitialCode: 'HACATBC',
  MakerKana: '',
  PlatformID: '',
  Price: '',
  SalesDate: '',
  ScreenshotImgFlg: 0
};

export const JAPANESE_GAME_FAIL: GameJP = {
  LinkURL: 'fail',
  Hard: 'sample',
  LinkTarget: 'sample',
  MakerName: 'sample',
  Memo: 'sample',
  D: new Date().getTime(),
  SalesDateStr: 'sample',
  ScreenshotImgURL: 'https://example.com/HAC12345',
  ComingThumb: 'sample',
  ThumbVariation: 'sample',
  SoftType: 'sample',
  TitleName: 'sample',
  TitleNameRuby: 'sample',
  InitialCode: 'HACATBC',
  MakerKana: '',
  PlatformID: '',
  Price: '',
  SalesDate: '',
  ScreenshotImgFlg: 0
};

export const EUROPEAN_GAME: GameEU = {
  _version_: 1,
  add_on_content_b: false,
  age_rating_sorting_i: 42,
  age_rating_type: 'E',
  age_rating_value: 'E',
  change_date: new Date(),
  cloud_saves_b: false,
  club_nintendo: true,
  compatible_controller: ['Xbox', 'PS4'],
  copyright_s: 'FOSS',
  date_from: new Date(2017, 3),
  dates_released_dts: [new Date()],
  deprioritise_b: false,
  developer: 'The World',
  digital_version_b: true,
  eshop_removed_b: false,
  excerpt: 'A very cool game',
  fs_id: 'id',
  game_categories_txt: ['sample'],
  game_category: ['sample'],
  game_series_t: 'series',
  gift_finder_carousel_image_url_s: 'https://url.com',
  gift_finder_description_s: 'descr',
  gift_finder_detail_page_image_url_s: 'https://url.com',
  gift_finder_detail_page_store_link_s: 'https://url.com',
  gift_finder_wishlist_image_url_s: 'https://url.com',
  hits_i: 42,
  image_url_h2x1_s: 'https://url.com',
  image_url_sq_s: 'https://url.com',
  image_url_tm_s: 'https://url.com',
  image_url: 'https://url.com',
  language_availability: ['en'],
  near_field_comm_b: true,
  nsuid_txt: ['12345678912345', 'nope', 'not this one'],
  originally_for_t: '5',
  pg_s: 'E',
  physical_version_b: true,
  play_mode_handheld_mode_b: true,
  play_mode_tabletop_mode_b: true,
  play_mode_tv_mode_b: true,
  playable_on_txt: ['xbox'],
  players_from: 1,
  players_to: 200,
  popularity: 42,
  pretty_agerating_s: 'E',
  pretty_date_s: '2017-03-17',
  pretty_game_categories_txt: ['sample'],
  price_discount_percentage_f: 42,
  price_has_discount_b: true,
  price_lowest_f: 42,
  price_regular_f: 42,
  price_sorting_f: 42,
  priority: new Date(),
  product_catalog_description_s: 'descr',
  product_code_ss: ['HAC12345'],
  product_code_txt: ['HAC12345'],
  publisher: 'nintendo',
  sorting_title: 'sort',
  switch_game_voucher_b: true,
  system_names_txt: ['xbox'],
  system_type: ['console'],
  title_extras_txt: ['sample'],
  title: 'sample game',
  type: 'game',
  url: 'https://url.com',
  wishlist_email_banner460w_image_url_s: 'https://url.com',
  wishlist_email_banner640w_image_url_s: 'https://url.com',
  wishlist_email_square_image_url_s: 'https://url.com'
};

export const AMERICAN_GAME: GameUS = {
  availability: [],
  boxart: 'https://media.nintendo.com/nintendo/bin/oiM2QlLg9frNJhSWvFGmi5NAvEAGlYVx/_3d_ldcR3G0YQl590uHXZ89Jmouu5aS9.png',
  description: '',
  developers: [],
  esrbDescriptors: [],
  esrbRating: '',
  featured: false,
  franchises: [],
  freeToStart: false,
  generalFilters: [],
  genres: ['Party', 'Multiplayer', 'Action'],
  horizontalHeaderImage: '',
  howToShop: [],
  lastModified: 1624052460484,
  lowestPrice: 49.99,
  msrp: 49.99,
  nsuid: '70010000000141',
  numOfPlayers: '2 players simultaneous',
  objectID: 'QY7EtPDIW1WGVWSEkQ7ZVLvCFvonU-Wl',
  platform: 'Nintendo Switch',
  playerFilters: [],
  priceRange: '',
  publishers: [],
  releaseDateDisplay: '2017-03-03T00:00:00.000Z',
  salePrice: null,
  slug: '1-2-switch',
  title: '1-2-Switch',
  url: ''
};
